---
- name: ensure the ssl directory exists
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0600
  tags:
    - nginx

- name: ensure the DH params are generated
  command: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 2048
  args:
    creates: /etc/nginx/ssl/dhparam.pem
  tags:
    - nginx

- name: Remove the default NGINX vhost file (if configured)
  file:
    name: "{{ dubzland_nginx_default_vhost_file }}"
    state: absent
  when: not dubzland_nginx_default_vhost_enabled
  notify: reload nginx
  tags:
    - nginx

- name: ensure any NGINX vhosts are configured
  template:
    src: "{{ item.template }}"
    dest: "{{ dubzland_nginx_vhost_path }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ dubzland_nginx_vhosts }}"
  notify: reload nginx
  tags:
    - nginx
