---
- name: ensure nginx is installed
  apt:
    name: nginx
    state: present
  tags:
    - nginx
    - apt

- name: ensure the default site is not configured
  file:
    name: "{{ _nginx_default_vhost_path }}"
    state: absent
  tags:
    - nginx

- name: ensure any vhosts are configured
  template:
    src: "{{ item.template }}"
    dest: "{{ _nginx_vhost_path }}/{{ item.filename }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ dubzland_nginx_vhosts }}"
  notify: reload nginx
  tags:
    - nginx

