---
- import_tasks: variables.yml
- import_tasks: packages.yml
- import_tasks: configuration.yml

- meta: flush_handlers

- name: ensure NGINX is running
  service:
    name: "{{ dubzland_nginx_service_name }}"
    state: started
